import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	// team, analytics
}: Readonly<{
	children: React.ReactNode;
	// team: React.ReactNode;
	// analytics: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* {team} */}
				{children}
				{/* {analytics} */}
				{/* <Link className="text-blue-500 block" href="/setting">Setting</Link> */}
			</body>
		</html>
	);
}
